/**
 * CodeRef2 Type System
 *
 * 26 type designators with validation, priorities, and metadata
 * per specification lines 503-526
 */

export enum TypeDesignator {
  F = 'F',       // File
  D = 'D',       // Directory
  C = 'C',       // Component
  Fn = 'Fn',     // Function
  Cl = 'Cl',     // Class
  M = 'M',       // Method
  V = 'V',       // Variable
  S = 'S',       // Style
  T = 'T',       // Test
  A = 'A',       // API Route
  Cfg = 'Cfg',   // Config
  H = 'H',       // Hook
  Ctx = 'Ctx',   // Context
  R = 'R',       // Redux
  Q = 'Q',       // Query
  I = 'I',       // Interface/Type
  Doc = 'Doc',   // Documentation
  Gen = 'Gen',   // Generated
  Dep = 'Dep',   // Dependency
  E = 'E',       // Event
  WIP = 'WIP',   // Work in Progress
  AST = 'AST'    // Abstract Syntax Tree
}

export enum TypePriority {
  High = 'High',
  Medium = 'Medium',
  Low = 'Low'
}

export interface TypeMetadata {
  name: string;
  description: string;
  priority: TypePriority;
  examples: string[];
}

export const TYPE_METADATA: Record<TypeDesignator, TypeMetadata> = {
  [TypeDesignator.F]: {
    name: 'File',
    description: 'Source code file or resource file',
    priority: TypePriority.High,
    examples: ['@F/src/parser.ts', '@F/packages/core/utils.js']
  },
  [TypeDesignator.D]: {
    name: 'Directory',
    description: 'Directory or folder path',
    priority: TypePriority.High,
    examples: ['@D/packages/core', '@D/src/components']
  },
  [TypeDesignator.C]: {
    name: 'Component',
    description: 'UI/Software component',
    priority: TypePriority.High,
    examples: ['@C/Button', '@C/Modal#open']
  },
  [TypeDesignator.Fn]: {
    name: 'Function',
    description: 'Function or exported function',
    priority: TypePriority.High,
    examples: ['@Fn/utils/logger#logInfo', '@Fn/core#parse']
  },
  [TypeDesignator.Cl]: {
    name: 'Class',
    description: 'Class definition',
    priority: TypePriority.High,
    examples: ['@Cl/Scanner', '@Cl/Parser#constructor']
  },
  [TypeDesignator.M]: {
    name: 'Method',
    description: 'Class method or instance method',
    priority: TypePriority.High,
    examples: ['@M/Parser#parse', '@M/Scanner#scan']
  },
  [TypeDesignator.V]: {
    name: 'Variable',
    description: 'Variable or constant declaration',
    priority: TypePriority.Medium,
    examples: ['@V/CONFIG', '@V/buffer']
  },
  [TypeDesignator.S]: {
    name: 'Style',
    description: 'CSS/styling definition',
    priority: TypePriority.Medium,
    examples: ['@S/Button.css#primary', '@S/colors']
  },
  [TypeDesignator.T]: {
    name: 'Test',
    description: 'Test case or test suite',
    priority: TypePriority.Medium,
    examples: ['@T/parser.test#shouldParse', '@T/validator.spec']
  },
  [TypeDesignator.A]: {
    name: 'API Route',
    description: 'API endpoint or route handler',
    priority: TypePriority.High,
    examples: ['@A/users/GET', '@A/api/validate']
  },
  [TypeDesignator.Cfg]: {
    name: 'Config',
    description: 'Configuration file or setting',
    priority: TypePriority.Medium,
    examples: ['@Cfg/tsconfig.json', '@Cfg/webpack.config']
  },
  [TypeDesignator.H]: {
    name: 'Hook',
    description: 'React hook or lifecycle hook',
    priority: TypePriority.High,
    examples: ['@H/useAuth', '@H/useEffect']
  },
  [TypeDesignator.Ctx]: {
    name: 'Context',
    description: 'Context provider or context consumer',
    priority: TypePriority.High,
    examples: ['@Ctx/AuthContext', '@Ctx/ThemeProvider']
  },
  [TypeDesignator.R]: {
    name: 'Redux',
    description: 'Redux store, action, or reducer',
    priority: TypePriority.Medium,
    examples: ['@R/userSlice', '@R/actions/setUser']
  },
  [TypeDesignator.Q]: {
    name: 'Query',
    description: 'Database query or GraphQL query',
    priority: TypePriority.Medium,
    examples: ['@Q/getUsersQuery', '@Q/findById']
  },
  [TypeDesignator.I]: {
    name: 'Interface/Type',
    description: 'TypeScript interface or type alias',
    priority: TypePriority.Medium,
    examples: ['@I/User', '@I/ParsedCodeRef']
  },
  [TypeDesignator.Doc]: {
    name: 'Documentation',
    description: 'Documentation file or comment',
    priority: TypePriority.Low,
    examples: ['@Doc/README#installation', '@Doc/API-guide']
  },
  [TypeDesignator.Gen]: {
    name: 'Generated Code',
    description: 'Code generated by tools',
    priority: TypePriority.Medium,
    examples: ['@Gen/types.generated.ts', '@Gen/schema']
  },
  [TypeDesignator.Dep]: {
    name: 'Dependency',
    description: 'External dependency or import',
    priority: TypePriority.Medium,
    examples: ['@Dep/react', '@Dep/@types/node']
  },
  [TypeDesignator.E]: {
    name: 'Event',
    description: 'Event emitter or event handler',
    priority: TypePriority.High,
    examples: ['@E/onClick', '@E/onChange']
  },
  [TypeDesignator.WIP]: {
    name: 'Work in Progress',
    description: 'Incomplete or experimental code',
    priority: TypePriority.Low,
    examples: ['@WIP/newFeature', '@WIP/refactoring']
  },
  [TypeDesignator.AST]: {
    name: 'AST Node',
    description: 'Abstract Syntax Tree node',
    priority: TypePriority.High,
    examples: ['@AST/Program', '@AST/FunctionDeclaration']
  }
};

/**
 * Validate type designator
 */
export function isValidTypeDesignator(type: string): boolean {
  return Object.values(TypeDesignator).includes(type as TypeDesignator) ||
         type === 'ML' || type === 'DB' || type === 'SEC'; // Extended types
}

/**
 * Get type metadata
 */
export function getTypeMetadata(type: string): TypeMetadata | null {
  const designator = type as TypeDesignator;
  return TYPE_METADATA[designator] || null;
}

/**
 * Get type priority
 */
export function getTypePriority(type: string): TypePriority {
  const metadata = getTypeMetadata(type);
  return metadata?.priority || TypePriority.Medium;
}

/**
 * Get all high-priority types
 */
export function getHighPriorityTypes(): string[] {
  return Object.entries(TYPE_METADATA)
    .filter(([_, meta]) => meta.priority === TypePriority.High)
    .map(([type, _]) => type);
}

/**
 * Get all types by priority
 */
export function getTypesByPriority(priority: TypePriority): string[] {
  return Object.entries(TYPE_METADATA)
    .filter(([_, meta]) => meta.priority === priority)
    .map(([type, _]) => type);
}

/**
 * Represents a code element (function, class, etc.) found in the codebase
 * MIGRATED FROM ROOT types.ts - Phase 1 Type Migration
 * EXTENDED for Phase 1: AST Integration - Added interface, type, decorator, property types
 */
export interface ElementData {
  type: 'function' | 'class' | 'component' | 'hook' | 'method' | 'constant' | 'interface' | 'type' | 'decorator' | 'property' | 'unknown';
  name: string;
  file: string;
  line: number;
  /** Optional: Whether the element is exported */
  exported?: boolean;
  /** Optional: Function/method parameters (from AST analysis) */
  parameters?: string[];
  /** Optional: Functions/methods called by this element (from AST analysis) */
  calls?: string[];
}

/**
 * Options for scanning code elements
 * MIGRATED FROM ROOT types.ts - Phase 1 Type Migration
 * EXTENDED for Phase 1: AST Integration - Added useAST and fallbackToRegex flags
 */
export interface ScanOptions {
  /** Glob pattern for file inclusion */
  include?: string | string[];
  /** Glob pattern for file exclusion */
  exclude?: string | string[];
  /** Scan recursively into subdirectories */
  recursive?: boolean;
  /** Languages to scan (file extensions) */
  langs?: string[];
  /** Custom patterns to use for scanning */
  customPatterns?: Array<{
    type: ElementData['type'];
    pattern: RegExp;
    nameGroup: number;
    lang: string;
  }>;
  /** Whether to include comments in the scan */
  includeComments?: boolean;
  /** Whether to show verbose output */
  verbose?: boolean;
  /**
   * Phase 1: AST Integration
   * Use AST-based parsing for TypeScript/JavaScript instead of regex (default: false)
   * Improves accuracy from 85% to 95%+ but adds ~50ms per file overhead
   */
  useAST?: boolean;
  /**
   * Phase 1: AST Integration
   * Fallback to regex patterns if AST parsing fails (default: true)
   * Ensures scan completes even with syntax errors
   */
  fallbackToRegex?: boolean;
  /**
   * Phase 2: Parallel Processing
   * Enable parallel file processing with worker threads (default: false)
   * Can be boolean or config object: { workers: number }
   * Provides 3-5x performance boost on large projects (500+ files)
   */
  parallel?: boolean | {
    /** Number of worker threads (default: CPU cores - 1) */
    workers?: number;
  };
  /**
   * Phase 2: Parallel Processing
   * Number of worker threads to use (deprecated: use parallel.workers instead)
   * Only used if parallel is true (default: os.cpus().length - 1)
   */
  workerPoolSize?: number;
}
